# Site settings
title: Next Day Ventures
description: Bringing Technical Startups to Market Fast
cover: assets/images/nextdayventures_hero.jpg
logo: assets/images/logo.png
favicon: assets/images/logo.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://nextdayventures.com" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
# facebook: ?
# twitter: ?
# github:  Next-Day-Ventures

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: Next-Day-Ventures #github username
repo: landing #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://nextdayventures.com/
source_url:  https://github.com/Next-Day-Ventures/landing #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
